language: node_js
node_js: '8'
before_install:
- openssl aes-256-cbc -K $encrypted_6a0cd62280ec_key -iv $encrypted_6a0cd62280ec_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
addons:
  ssh_known_hosts: 35.184.248.205
after_success: sh .travis/deploy.sh
