language: node_js
node_js: '8'
before_install:
- openssl aes-256-cbc -K $encrypted_f539ffa82348_key -iv $encrypted_f539ffa82348_iv
  -in deploy_key.enc -out deploy_key -d

addons:
  ssh_known_hosts: 35.184.248.205
after_success: sh .travis/deploy.sh
